### PR TITLE
Include <stdbool.h> instead of redefining `bool`, `true` and `false` keywords

### LINKED ISSUE #1049: Build failure with GCC 15 (defaults to -std=gnu23)
Upcoming GCC 15 defaults to `-std=gnu23` and libsndfile fails to build with it as follows:
```
libtool: compile:  x86_64-pc-linux-gnu-gcc -m32 -mfpmath=sse -DHAVE_CONFIG_H -I. -I/var/tmp/portage/media-libs/libsndfile-1.2.2-r2/work/libsndfile-1.2.2 -I./src -I/var/tmp/portage/media-libs/libsndfile-1.2.2-r2/work/libsndfile-1.2.2/src -I/var/tmp/portage/media-libs/libsndfile-1.2.2-r2/work/libsndfile-1.2.2/include -I./include -O2 -march=native -pipe -flto -Wall -Wextra -Wpointer-arith -Wcast-align -Wcast-qual -Wshadow -Wwrite-strings -Wundef -Wuninitialized -Winit-self -Wno-format-truncation -Wvla -Wbad-function-cast -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Waggregate-return -c /var/tmp/portage/media-libs/libsndfile-1.2.2-r2/work/libsndfile-1.2.2/src/ALAC/alac_decoder.c  -fPIC -DPIC -o src/ALAC/.libs/alac_decoder.o
/var/tmp/portage/media-libs/libsndfile-1.2.2-r2/work/libsndfile-1.2.2/src/ALAC/alac_decoder.c:42:9: error: expected identifier before 'false'
   42 | {       false = 0,
      |         ^~~~~
/var/tmp/portage/media-libs/libsndfile-1.2.2-r2/work/libsndfile-1.2.2/src/ALAC/alac_decoder.c:44:3: error: expected ';', identifier or '(' before 'bool'
   44 | } bool ;
      |   ^~~~
/var/tmp/portage/media-libs/libsndfile-1.2.2-r2/work/libsndfile-1.2.2/src/ALAC/alac_decoder.c:44:3: warning: useless type name in empty declaration
make[2]: *** [Makefile:2629: src/ALAC/alac_decoder.lo] Error 1
```

The issue is bool is a keyword in C23 so redefining it breaks. Originally reported downstream in Gentoo at https://bugs.gentoo.org/943864.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #1049

### CODE REVIEW

File: src/ALAC/alac_codec.h [hunk 1]
```diff
@@ -28,6 +28,18 @@
...
+#include <stdbool.h>
+#endif
+
+#if !defined(__cplusplus) && !defined(__bool_true_false_are_defined)
+typedef enum
+{
+	false = 0,
+	true = 1
+} bool ;
+#endif
```
Comment (SoapGentoo) [inline src/ALAC/alac_codec.h:41]: nix this entire lot and just include `<stdbool.h>` in the headers/files that need it. It's 2024, if you dont have a C99 compiler, I'm sorry for you.

**Review by SoapGentoo — CHANGES_REQUESTED** [review]

**Review by SoapGentoo — APPROVED** [review]

**Comment by fabiangreffrath** [comment]
@SoapGentoo will you merge this?
